#include "Assets/Shaders/HLSL/AtlasParticles.hlsl"
#include "Assets/Shaders/HLSL/Random.hlsl"

#pragma kernel CSSleepingZs_Init
#pragma kernel CSSleepingZs_Update


RWStructuredBuffer<float3> _Output;

[numthreads(THREADS_PER_GROUP, 1, 1)]
void CSSleepingZs_Init (uint id : SV_DispatchThreadID)
{
    _Output[id] = float3(1, 1, 1);
}

[numthreads(THREADS_PER_GROUP, 1, 1)]
void CSSleepingZs_Update(uint id : SV_DispatchThreadID)
{
    _Output[id] = float3(1, 1, 1);
}
